### ISSUE TITLE
Washington Post modifies the paywall url

### ISSUE THREAD

**Issue by SaintWacko** [okhwaja/outline-extension#3]
Washington Post displays the url for a paywalled page as the root of the site, rendering the "Open in Outline" button non-functional. The currently open PR will fix this by allowing you to right-click a link and open the targeted link in Outline, I just didn't know of any other way to contact the author of this plugin to request that this PR be merged (I've tested it and it functions as intended).

**Comment by okhwaja** [comment]
Hey @SaintWacko , sorry I didn't notice this. I'm going to review my settings to make sure I see activity on this repo going forward.

I just merged and deployed https://github.com/okhwaja/outline-extension/pull/2

Thanks!

**Comment by SaintWacko** [comment]
Thank you!
