### ISSUE TITLE
Open links in outline by copying and pasting into menu

### ISSUE THREAD

**Issue by Sokushinbutsu** [okhwaja/outline-extension#7]
I use outline both to make pages more readable and to get around paywalls. One strategy for skirting paywalls is to use an url shortener before pasting the link into outline. If this extension had a dropdown menu for that purpose I think it would be more useful. I wouldn't mind spending some time doing this if you're open to merging the PR.

**Comment by okhwaja** [comment]
Hey @Sokushinbutsu - I'd be open to seeing what that looks like if you have the time

**Comment by vezaynk** [comment]
My changes in #10 make this unnecessary.
