### ISSUE TITLE
Doesn't work on mobile

### ISSUE THREAD

**Issue by amalic** [okhwaja/outline-extension#8]
Would be great if this would work with the mobile version of Firefox automatically for whitelisted domains.

**Comment by Sotilrac** [comment]
Hi @amalic and @okhwaja I made thois PR to adress this issue. I hope it helps.
https://github.com/okhwaja/outline-extension/pull/9

**Comment by okhwaja** [comment]
Hey @amalic and @Sotilrac - just published the new version. Any chance you can test if it works? I don't have an android device with me. Let me know!

**Comment by okhwaja** [comment]
Just used the new version on a device - Motorola e5 play, android oreo (8.0.0), and a fresh installation of Firefox (68.4.2).

I'm able to send the current url to outline via the more option menu([kebab menu](https://stackoverflow.com/questions/34755666/what-is-the-hamburger-menu-icon-called-and-the-three-vertical-dots-icon-called)) in the upper right-hand corner of the browser

Going to close for now - let me know if you see issues
